# Generated by Django 6.0.2 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_genre_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
